; Enter the paths to your game start/launch.bat
; [NAME] = [PATH TO BAT/EXE]
[Games]
Game1 = C:\Game1.bat
Game2 = C:\Game2.bat
Game3 = C:\Game1.bat
Game4 = C:\Game2.bat
Game5 = C:\Game1.bat
Game6 = C:\Game2.bat
Game7 = C:\Game1.bat
Game8 = C:\Game2.bat
Game9 = C:\Game1.bat
Game10 = C:\Game2.bat
Game11 = C:\Game1.bat
Game12 = C:\Game2.bat
Game13 = C:\Game1.bat
Game14 = C:\Game2.bat
Game15 = C:\Game1.bat
Game16 = C:\Game2.bat
Game17 = C:\Game1.bat
Game18 = C:\Game2.bat
Game19 = C:\Game1.bat
Game20 = C:\Game2.bat
Game21 = C:\Game1.bat
Game22 = C:\Game2.bat
Game23 = C:\Game1.bat
Game24 = C:\Game1.bat
Game25 = C:\Game2.bat
Game26 = C:\Game1.bat
Game27 = C:\Game2.bat
Game28 = C:\Game1.bat
Game29 = C:\Game2.bat
Game30 = C:\Game1.bat
Game31 = C:\Game2.bat